# Generated by Django 5.1.3 on 2024-12-31 02:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Police',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commissariat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='Commissariat')),
                ('arrondissement', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='Moto')),
                ('marque', models.CharField(max_length=255)),
                ('immatriculation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Papiers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('num_identification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Saisie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
