# Generated by Django 5.1.3 on 2024-12-31 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='Commissariat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='backend.commissariat'),
        ),
        migrations.AddField(
            model_name='moto',
            name='Saisie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='motos_saisies', to='backend.saisie'),
        ),
        migrations.AddField(
            model_name='moto',
            name='agent_police',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='motos_principaux', to='backend.agent_police'),
        ),
        migrations.AddField(
            model_name='papiers',
            name='Commissariat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papiers', to='backend.commissariat'),
        ),
        migrations.AddField(
            model_name='papiers',
            name='Saisie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papiers_verifies', to='backend.saisie'),
        ),
        migrations.AddField(
            model_name='papiers',
            name='agent_police',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papiers_emis', to='backend.agent_police'),
        ),
    ]
