# Generated by Django 5.1.3 on 2024-12-31 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_moto_commissariat_moto_saisie_moto_agent_police_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saisie',
            name='date',
        ),
    ]
