# Generated by Django 5.1.3 on 2025-01-08 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_quartier_commissariat_adresse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papiers',
            old_name='prenom',
            new_name='libellé',
        ),
        migrations.RemoveField(
            model_name='saisie',
            name='date',
        ),
        migrations.AddField(
            model_name='moto',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='papiers',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
